second lesson tasks from lab and homework
ezjust/itea_python_base pull request #1
Opened 2019-06-10 19:39 UTC by ezjust

please confirm that homework done in proper way)

2019-06-10 19:50 UTC, itea-artem requested changes

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +#1
why this code in comments?

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +# def Isprime(n):
```suggestion
# def is_prime(n):
```

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +# summ = 0
```suggestion
# sum = 0
```

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +#     for i in range(1,(n+1)):
```suggestion
#     for i in range(1, n+1):
```

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +# for i in range(1,(n+1)):
PEP8
```suggestion
# for i in range(1, n+1):
```

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +# a, b = list(map(int, input("Insert two values separated by comma: ").split(',')))
```suggestion
# a, b = map(int, input("Insert two values separated by comma: ").split(','))
```

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +#     print(a,b)
PEP8

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +#     ran = random.randint(int(a),int(b))
remove ints

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +#             continue
no need for continue here

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_home_tasks.py
> +#             continue
no need for continue here

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_tasks.py
> +# a=0
PEP8

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_tasks.py
> +# while a<=1000:
Wrong.

2019-06-10 19:50 UTC, itea-artem commented on second_lesson_tasks.py
> +#     if i.isupper() is True:
```suggestion
#     if i.isupper():
```

2019-06-10 20:17 UTC, ezjust commented on second_lesson_home_tasks.py
> +#             continue
removed

2019-06-10 20:17 UTC, ezjust commented on second_lesson_home_tasks.py
> +#             continue
removed

2019-06-10 20:35 UTC, ezjust reviewed
fixed all mistakes marked in scripts

2019-06-14 17:18 UTC, ezjust commented
updated, fixed all mistakes, please recheck

2019-06-14 18:02 UTC, itea-artem requested changes

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_home_tasks.py
> +        print('NO it is not prime number')
return

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_home_tasks.py
> +
Blank

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_tasks.py
> +    if i.isupper() is True:
```suggestion
    if i.isupper()
```

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_tasks.py
> +    if value == 0:
Unnecessary check

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_tasks.py
> +def average_value(list):
```suggestion
def get_average_value(list):
```

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_tasks.py
> +        return print(list2)
```suggestion
        return list2
```

2019-06-14 18:02 UTC, itea-artem commented on second_lesson_tasks.py
> +
blank

2019-06-16 18:38 UTC, itea-artem requested changes

2019-06-16 18:38 UTC, itea-artem commented on second_lesson_tasks.py
> +    print(digit, end=" ")
New line

2019-06-16 18:38 UTC, itea-artem commented on second_lesson_tasks.py
> +    v_list.append(i)
```suggestion
    i = int(input('input any int: '))
    v_list.append(i)
```

2019-06-16 18:38 UTC, itea-artem commented on second_lesson_tasks.py
> +    if i == 0:
remove this

2019-06-16 18:38 UTC, itea-artem commented on second_lesson_tasks.py
> +for i in range(0, 64):
What if number == 2**100? This is recursion task

2019-06-18 18:53 UTC, ezjust commented on second_lesson_tasks.py
> +    print(digit, end=" ")
didn't get what is the problem here?

2019-06-24 20:52 UTC, itea-artem requested changes
4/5.5

2019-06-24 20:52 UTC, itea-artem commented on check_if_value_simple.py
> +def is_prime(num):
2) Если функция возвращает True/False, она должна начинаться с is

2019-06-24 20:52 UTC, itea-artem commented on check_power_of_two.py
> +for i in range(0, 64):
incorrect result for 2**65

2019-06-24 20:52 UTC, itea-artem commented on cycle_power_integer.py
> +    print(value*value)
Ваш код должен соблюдать pep8.

2019-06-24 20:52 UTC, itea-artem commented on paint_triangle.py
> +    print(line_pic.center(num*2, ' '))
Ваш код должен соблюдать pep8.

2019-06-24 20:52 UTC, itea-artem commented on recursion_function_sum_digits.py
> +        sum_digits([33, 14, 15])
hardcoded data?

2019-06-25 14:01 UTC, merged