4th lesson another try
ezjust/itea_python_base pull request #7
Opened 2019-07-02 15:04 UTC by ezjust

2019-07-05 08:11 UTC, Art17 requested changes

2019-07-05 08:11 UTC, Art17 commented on gen_random_list.py
> +        last_same_counter.append(count_same)
No need in this list. Just use max_count_same variable and update it on every iteration with max fn.

2019-07-05 08:11 UTC, Art17 commented on remove_by_index_value.py
> +            my_list = my_list[:i] + my_list[i+1:]
No need in cycle
```suggestion
            my_list = my_list[:index] + my_list[index+1:]
```

2019-07-05 08:11 UTC, Art17 commented on remove_by_index_value.py
> +    exist = 0
This var should be bool.

2019-07-05 08:11 UTC, Art17 commented on replace_split_find.py
> +def split_string(sentence='this is the string'):
pass splitter as an argument

2019-07-05 08:11 UTC, Art17 commented on replace_split_find.py
> +            split_values.append(tmp)
No need in tmp. Find indices and use slices

2019-07-05 08:11 UTC, Art17 commented on replace_split_find.py
> +def replace_string(input_string='it is the test test test', sub_string='test', matches=2, new_sub_string='result'):
Function will not work for
`
input_string = 'testhello'
sub_string = 'hello'
`

2019-07-05 08:11 UTC, Art17 commented on replace_split_find.py
> +def find_sub_string(input_string='this istest test', sub_string='e', start_c=0, end_c=15):
Will not work if `len(sub_string) >= 2`

2019-07-12 22:13 UTC, itea-artem approved these changes
5/8

2019-07-12 22:13 UTC, itea-artem commented on gen_random_list.py
> +last_same_counter = []
remove this line

2019-07-12 22:13 UTC, itea-artem commented on gen_random_list.py
> +last_number = []
remove this line

2019-07-12 22:13 UTC, itea-artem commented on remove_by_index_value.py
> +        raise ValueOutOfRange("index is bigger than length of list, set index properly")
В функции делайте raise только своих исключений. Не надо делать проверку, например, на то что индекс валидный, так как это исключение сделает питон и надо будет эту функцию обернуть в try-except. А так получается вы переопределяете стандартное исключение.

2019-07-12 22:13 UTC, itea-artem commented on remove_by_index_value.py
> +        raise NoValueInList('There is no value = "{}" in provided list'.format(value))
Тут уже нормальное применение, так как в питоне нет стандартного исключения NoValueInList..

2019-07-12 22:13 UTC, itea-artem commented on replace_split_find.py
> +        result = re.sub(r'{}'.format(sub_string), '{}'.format(new_sub_string), '{}'.format(input_string))
Почему в остальных функциях проходите циклом, а тут используете re?

2019-07-12 22:13 UTC, itea-artem commented on replace_split_find.py
> +            if input_string[i] == sub_string and counter <= end_c:
Не будет работать если sub_string='123'

2019-07-12 22:13 UTC, itea-artem commented on replace_split_find.py
> +def remove_by_index(input_string='this istest test', index_remove=[1, 2, 100]):
remove_by_index -> значит index должен быть один
https://github.com/cyr1z/ITEA_Python_Basics/pull/4/files#diff-adc8d271a59d0fd4678935c38e29174fR5

2019-07-12 22:13 UTC, itea-artem commented on replace_split_find.py
> +def remove_by_substring(input_string='this istest test', char_remove='e'):
https://github.com/cyr1z/ITEA_Python_Basics/pull/4/files#diff-adc8d271a59d0fd4678935c38e29174fR9

2019-07-14 16:28 UTC, merged